services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    build:
      context: .
      target: builder
    command: npm run build

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    depends_on:
      - app
